// ============================================================
// BABY MEDIA LIBRARY 
// Videos categorized by Baby Care Topics and Age
// ============================================================

export const BABY_VIDEO_LIBRARY = {
  'Baby Feeding': [
    {
      id: 'bf1',
      title: 'Breastfeeding Basics & How to Latch',
      category: 'Baby Feeding',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['breastfeeding', 'latch', 'mother milk'],
      url: 'https://www.youtube.com/results?search_query=how+to+breastfeed+a+baby+properly+latch',
      description: 'Techniques for feeding mother\'s milk and ensuring baby latches properly.',
      emoji: '🤱',
    },
    {
      id: 'bf2',
      title: 'What to Do if Baby is Not Latching',
      category: 'Baby Feeding',
      ages: [1, 2, 3, 4],
      tags: ['latch', 'not latching', 'struggling'],
      url: 'https://www.youtube.com/results?search_query=what+to+do+if+baby+wont+latch+breastfeeding',
      description: 'Solutions for when your baby is having trouble sucking or latching properly.',
      emoji: '⚠️',
    },
    {
      id: 'bf3',
      title: 'How to Prepare and Give Formula Milk',
      category: 'Baby Feeding',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['formula', 'bottle', 'preparation'],
      url: 'https://www.youtube.com/results?search_query=how+to+prepare+formula+milk+for+baby',
      description: 'Safe preparation and feeding methods for formula milk.',
      emoji: '🍼',
    },
    {
      id: 'bf4',
      title: 'How to Use Feeding Bottles Correctly',
      category: 'Baby Feeding',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['bottle feeding', 'bottles'],
      url: 'https://www.youtube.com/results?search_query=how+to+bottle+feed+a+baby+paced+feeding',
      description: 'Tips on using feeding bottles, including paced bottle feeding.',
      emoji: '🍼',
    },
    {
      id: 'bf5',
      title: 'How to Pump Breast Milk Effectively',
      category: 'Baby Feeding',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['pumping', 'breast pump', 'store milk'],
      url: 'https://www.youtube.com/results?search_query=how+to+pump+breast+milk+and+store',
      description: 'Techniques for pumping and storing breast milk for each month.',
      emoji: '💧',
    },
    {
      id: 'bf6',
      title: 'How to Burp Your Baby',
      category: 'Baby Feeding',
      ages: [1, 2, 3, 4, 5, 6],
      tags: ['burping', 'gas'],
      url: 'https://www.youtube.com/results?search_query=how+to+burp+a+newborn+baby',
      description: 'Essential techniques for burping your baby effectively to avoid gas.',
      emoji: '🌬️',
    },
    {
      id: 'bf7',
      title: 'Feeding Schedules for 1-3 Month Olds',
      category: 'Baby Feeding',
      ages: [1, 2, 3],
      tags: ['schedule', 'routine'],
      url: 'https://www.youtube.com/results?search_query=feeding+schedule+for+1+to+3+month+old+baby',
      description: 'How often you should feed your newborn to 3-month-old baby.',
      emoji: '⏰',
    },
    {
      id: 'bf8',
      title: 'Feeding Schedules for 4-6 Month Olds',
      category: 'Baby Feeding',
      ages: [4, 5, 6],
      tags: ['schedule', 'routine'],
      url: 'https://www.youtube.com/results?search_query=feeding+schedule+for+4+to+6+month+old+baby',
      description: 'Adjusting feeding schedules as your baby grows.',
      emoji: '⏰',
    },
  ],

  'Baby Food': [
    {
      id: 'bfd1',
      title: 'When and How to Start Solid Foods',
      category: 'Baby Food',
      ages: [5, 6, 7],
      tags: ['solids', 'weaning', 'start'],
      url: 'https://www.youtube.com/results?search_query=how+and+when+to+start+solid+foods+for+baby',
      description: 'A complete guide to starting solid foods (weaning).',
      emoji: '🥣',
    },
    {
      id: 'bfd2',
      title: 'First Foods for 6 Month Old Babies',
      category: 'Baby Food',
      ages: [6],
      tags: ['6 months', 'first foods', 'puree'],
      url: 'https://www.youtube.com/results?search_query=best+first+foods+for+6+month+old+baby',
      description: 'Safe and healthy purees for your 6-month-old.',
      emoji: '🥕',
    },
    {
      id: 'bfd3',
      title: 'Safe vs Unsafe Foods for Babies',
      category: 'Baby Food',
      ages: [6, 7, 8, 9, 10, 11, 12],
      tags: ['safe foods', 'choking hazard', 'unsafe'],
      url: 'https://www.youtube.com/results?search_query=foods+to+avoid+giving+baby+under+1+year',
      description: 'Which foods you should give and which to absolutely avoid.',
      emoji: '🚫',
    },
    {
      id: 'bfd4',
      title: 'Healthy Baby Diet Plans (7-9 Months)',
      category: 'Baby Food',
      ages: [7, 8, 9],
      tags: ['diet', 'meal plan', '7-9 months'],
      url: 'https://www.youtube.com/results?search_query=baby+food+meal+plan+7+8+9+months',
      description: 'Feeding routines and meal prep for 7 to 9-month-old babies.',
      emoji: '🥦',
    },
    {
      id: 'bfd5',
      title: 'Finger Foods and Portion Control (10-12 Months)',
      category: 'Baby Food',
      ages: [10, 11, 12],
      tags: ['finger foods', 'portion', '10-12 months'],
      url: 'https://www.youtube.com/results?search_query=baby+finger+foods+10+to+12+months',
      description: 'How to introduce finger foods and maintain portion control.',
      emoji: '🍌',
    },
  ],

  'Baby Sleep': [
    {
      id: 'bs1',
      title: 'How to Calm a Crying Baby',
      category: 'Baby Sleep',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['crying', 'soothing', 'calm'],
      url: 'https://www.youtube.com/results?search_query=how+to+calm+a+crying+baby+instantly',
      description: 'Effective tips to soothe and calm a crying baby.',
      emoji: '🌙',
    },
    {
      id: 'bs2',
      title: 'Baby Sleep Routines and Tips',
      category: 'Baby Sleep',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['sleep', 'routine', 'night time'],
      url: 'https://www.youtube.com/results?search_query=how+to+get+baby+to+sleep+through+the+night',
      description: 'Tips for establishing a healthy sleep schedule.',
      emoji: '😴',
    },
    {
      id: 'bs3',
      title: 'Safe Sleep Guidelines for Infants',
      category: 'Baby Sleep',
      ages: [1, 2, 3, 4, 5, 6],
      tags: ['safe sleep', 'guidelines'],
      url: 'https://www.youtube.com/results?search_query=safe+sleep+guidelines+for+babies',
      description: 'Important guidelines for safe baby sleep.',
      emoji: '🛌',
    },
  ],

  'Baby Health': [
    {
      id: 'bh1',
      title: 'What to Do When Baby Turns Yellow (Jaundice)',
      category: 'Baby Health',
      ages: [1, 2],
      tags: ['jaundice', 'yellow', 'health'],
      url: 'https://www.youtube.com/results?search_query=newborn+baby+jaundice+what+to+do',
      description: 'Signs of jaundice in newborns and when to seek medical help.',
      emoji: '⚠️',
    },
    {
      id: 'bh2',
      title: 'Common Feeding Problems and Solutions',
      category: 'Baby Health',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['feeding issues', 'spit up', 'reflux'],
      url: 'https://www.youtube.com/results?search_query=baby+feeding+problems+reflux+spit+up',
      description: 'How to handle common feeding issues like reflux and spitting up.',
      emoji: '🏥',
    },
    {
      id: 'bh3',
      title: 'When to Seek Medical Help for Your Baby',
      category: 'Baby Health',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['emergency', 'fever', 'doctor'],
      url: 'https://www.youtube.com/results?search_query=when+to+take+baby+to+hospital+or+doctor',
      description: 'Warning signs that require immediate medical attention.',
      emoji: '🌡️',
    },
  ],

  'Baby Development': [
    {
      id: 'bd1',
      title: 'How to Identify if Baby is Full or Hungry',
      category: 'Baby Development',
      ages: [1, 2, 3, 4, 5, 6],
      tags: ['hunger cues', 'fullness', 'signs'],
      url: 'https://www.youtube.com/results?search_query=baby+hunger+cues+fullness+signs',
      description: 'Learn to read your baby\'s cues for hunger and fullness.',
      emoji: '👶',
    },
    {
      id: 'bd2',
      title: 'How to Change a Diaper Properly',
      category: 'Baby Development',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['diaper', 'change', 'hygiene'],
      url: 'https://www.youtube.com/results?search_query=how+to+change+a+baby+diaper',
      description: 'Step-by-step guide to changing diapers and preventing rash.',
      emoji: '🧷',
    },
    {
      id: 'bd3',
      title: 'Baby Bathing and Hygiene Basics',
      category: 'Baby Development',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['bath', 'hygiene', 'wash'],
      url: 'https://www.youtube.com/results?search_query=how+to+bathe+a+newborn+baby',
      description: 'How to safely give your baby a bath and maintain hygiene.',
      emoji: '🛁',
    },
  ],

  'Mother Care': [
    {
      id: 'mc1',
      title: 'Postpartum Recovery Tips',
      category: 'Mother Care',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['recovery', 'postpartum', 'self care'],
      url: 'https://www.youtube.com/results?search_query=postpartum+recovery+tips+for+new+moms',
      description: 'How to take care of yourself after birth.',
      emoji: '🌸',
    },
  ],
};
