// ============================================================
// BABY MEDIA LIBRARY 
// Videos categorized by Baby Care Topics and Age
// ============================================================

export const BABY_VIDEO_LIBRARY = {
  'Baby Feeding': [
    {
      id: 'bf1',
      title: 'Breastfeeding Basics & How to Latch',
      category: 'Baby Feeding',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['breastfeeding', 'latch', 'mother milk'],
      url: 'https://www.youtube.com/results?search_query=how+to+breastfeed+a+baby+properly+latch',
      description: 'Techniques for feeding mother\'s milk and ensuring baby latches properly.',
      emoji: '🤱',
    },
    {
      id: 'bf2',
      title: 'What to Do if Baby is Not Latching',
      category: 'Baby Feeding',
      ages: [1, 2, 3, 4],
      tags: ['latch', 'not latching', 'struggling'],
      url: 'https://www.youtube.com/results?search_query=what+to+do+if+baby+wont+latch+breastfeeding',
      description: 'Solutions for when your baby is having trouble sucking or latching properly.',
      emoji: '⚠️',
    },
    {
      id: 'bf3',
      title: 'How to Prepare and Give Formula Milk',
      category: 'Baby Feeding',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['formula', 'bottle', 'preparation'],
      url: 'https://www.youtube.com/results?search_query=how+to+prepare+formula+milk+for+baby',
      description: 'Safe preparation and feeding methods for formula milk.',
      emoji: '🍼',
    },
    {
      id: 'bf4',
      title: 'How to Burp Your Baby Effectively',
      category: 'Baby Feeding',
      ages: [1, 2, 3, 4, 5, 6],
      tags: ['burping', 'gas'],
      url: 'https://www.youtube.com/results?search_query=how+to+burp+a+newborn+baby',
      description: 'Essential techniques for burping your baby effectively to avoid gas.',
      emoji: '🌬️',
    },
  ],

  'Baby Bathing': [
    {
      id: 'bb1',
      title: 'How to Bathe a Newborn Baby Safely',
      category: 'Baby Bathing',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['bath', 'newborn bath', 'bathing', 'clean'],
      url: 'https://www.youtube.com/results?search_query=how+to+bathe+a+newborn+baby+safely',
      description: 'Step-by-step tutorial on safely holding and bathing your newborn baby.',
      emoji: '🛁',
    },
    {
      id: 'bb2',
      title: 'Sponge Bath Tutorial for Newborns',
      category: 'Baby Bathing',
      ages: [1, 2, 3, 4],
      tags: ['sponge bath', 'first bath', 'newborn'],
      url: 'https://www.youtube.com/results?search_query=sponge+bath+tutorial+for+newborn',
      description: 'How to give your newborn a gentle sponge bath before umbilical cord falls off.',
      emoji: '🧽',
    },
    {
      id: 'bb3',
      title: 'Umbilical Cord Care During & After Bath',
      category: 'Baby Bathing',
      ages: [1, 2, 3],
      tags: ['umbilical cord', 'cord care', 'cleaning'],
      url: 'https://www.youtube.com/results?search_query=umbilical+cord+care+during+baby+bath',
      description: 'How to clean and care for the umbilical cord area safely while bathing.',
      emoji: '🩺',
    },
    {
      id: 'bb4',
      title: 'Safe & Calm Baby Bath Routine',
      category: 'Baby Bathing',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['bath routine', 'water temperature', 'safety'],
      url: 'https://www.youtube.com/results?search_query=safe+and+calm+baby+bath+routine',
      description: 'Setting ideal water temperature and creating a calm bathing experience.',
      emoji: '💧',
    },
  ],

  'Baby Diapering': [
    {
      id: 'bdp1',
      title: 'How to Change a Newborn Baby Diaper',
      category: 'Baby Diapering',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['diaper', 'change diaper', 'dress diaper', 'nappy'],
      url: 'https://www.youtube.com/results?search_query=how+to+change+a+newborn+baby+diaper',
      description: 'Step-by-step guide to changing newborn diapers cleanly and comfortably.',
      emoji: '🧷',
    },
    {
      id: 'bdp2',
      title: 'Newborn Diaper Changing Step-by-Step',
      category: 'Baby Diapering',
      ages: [1, 2, 3, 4],
      tags: ['changing diaper', 'put diaper', 'guide'],
      url: 'https://www.youtube.com/results?search_query=newborn+diaper+changing+step+by+step',
      description: 'Beginner tutorial on putting on and securing diapers for boys and girls.',
      emoji: '👶',
    },
    {
      id: 'bdp3',
      title: 'Preventing & Treating Diaper Rash',
      category: 'Baby Diapering',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['diaper rash', 'rash cream', 'prevention'],
      url: 'https://www.youtube.com/results?search_query=preventing+and+treating+diaper+rash',
      description: 'How to prevent redness, treat diaper rashes, and use barrier creams.',
      emoji: '🌸',
    },
    {
      id: 'bdp4',
      title: 'Choosing Correct Diaper Size & Fit Guide',
      category: 'Baby Diapering',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['diaper size', 'leak prevention', 'fit'],
      url: 'https://www.youtube.com/results?search_query=choosing+correct+diaper+size+baby',
      description: 'How to prevent leaks and blowouts by picking the right diaper size.',
      emoji: '📐',
    },
  ],

  'Baby Sleeping': [
    {
      id: 'bs1',
      title: 'Baby Sleep Routines & How to Help Baby Sleep',
      category: 'Baby Sleeping',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['sleep', 'routine', 'night time'],
      url: 'https://www.youtube.com/results?search_query=how+to+get+baby+to+sleep+through+the+night',
      description: 'Tips for establishing a healthy sleep schedule.',
      emoji: '😴',
    },
    {
      id: 'bs2',
      title: 'Safe Sleep Guidelines for Infants',
      category: 'Baby Sleeping',
      ages: [1, 2, 3, 4, 5, 6],
      tags: ['safe sleep', 'guidelines'],
      url: 'https://www.youtube.com/results?search_query=safe+sleep+guidelines+for+babies',
      description: 'Important guidelines for safe baby sleep.',
      emoji: '🛌',
    },
    {
      id: 'bs3',
      title: 'How to Soothe a Restless Baby at Night',
      category: 'Baby Sleeping',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['restless', 'night sleep', 'soothing'],
      url: 'https://www.youtube.com/results?search_query=how+to+soothe+restless+baby+at+night',
      description: 'Techniques for helping a restless baby settle back to sleep.',
      emoji: '🌙',
    },
  ],

  'Baby Crying': [
    {
      id: 'bc1',
      title: 'How to Calm a Crying Baby Instantly',
      category: 'Baby Crying',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['crying', 'soothing', 'calm'],
      url: 'https://www.youtube.com/results?search_query=how+to+calm+a+crying+baby+instantly',
      description: 'Proven techniques (5 S\'s) to calm a fussy or crying baby.',
      emoji: '😭',
    },
    {
      id: 'bc2',
      title: 'Understanding Colic & Soothing Techniques',
      category: 'Baby Crying',
      ages: [1, 2, 3, 4],
      tags: ['colic', 'gas', 'fussy'],
      url: 'https://www.youtube.com/results?search_query=understanding+colic+and+soothing+techniques',
      description: 'How to comfort a baby suffering from colic or gas pains.',
      emoji: '🧸',
    },
  ],

  'Baby Health': [
    {
      id: 'bh1',
      title: 'What to Do When Baby Has a Fever',
      category: 'Baby Health',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['fever', 'temperature', 'sick'],
      url: 'https://www.youtube.com/results?search_query=what+to+do+when+baby+has+a+fever',
      description: 'How to measure temperature and safely care for a feverish baby.',
      emoji: '🌡️',
    },
    {
      id: 'bh2',
      title: 'What to Do When Baby Turns Yellow (Jaundice)',
      category: 'Baby Health',
      ages: [1, 2],
      tags: ['jaundice', 'yellow', 'health'],
      url: 'https://www.youtube.com/results?search_query=newborn+baby+jaundice+what+to+do',
      description: 'Signs of jaundice in newborns and when to seek medical help.',
      emoji: '⚠️',
    },
    {
      id: 'bh3',
      title: 'When to Seek Immediate Medical Help for Baby',
      category: 'Baby Health',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['emergency', 'doctor', 'hospital'],
      url: 'https://www.youtube.com/results?search_query=when+to+take+baby+to+hospital+or+doctor',
      description: 'Warning signs that require immediate medical attention.',
      emoji: '🏥',
    },
  ],

  'Baby Development': [
    {
      id: 'bd1',
      title: 'Baby Milestone Guide (0-12 Months)',
      category: 'Baby Development',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['milestones', 'growth', 'development'],
      url: 'https://www.youtube.com/results?search_query=baby+development+milestones+first+year',
      description: 'Key physical and mental development milestones for month 1-12.',
      emoji: '🌱',
    },
    {
      id: 'bd2',
      title: 'Tummy Time Exercises for Newborns',
      category: 'Baby Development',
      ages: [1, 2, 3, 4, 5, 6],
      tags: ['tummy time', 'neck strength'],
      url: 'https://www.youtube.com/results?search_query=tummy+time+exercises+for+newborns',
      description: 'How to start tummy time safely to build head and neck strength.',
      emoji: '👶',
    },
  ],

  'Vaccination': [
    {
      id: 'vac1',
      title: 'Baby Vaccination Schedule & What to Expect',
      category: 'Vaccination',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['vaccine', 'vaccination', 'shots', 'clinic'],
      url: 'https://www.youtube.com/results?search_query=baby+vaccination+schedule+what+to+expect',
      description: 'Guide to essential baby immunizations and clinic visits.',
      emoji: '💉',
    },
    {
      id: 'vac2',
      title: 'How to Soothe Baby After Vaccines',
      category: 'Vaccination',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['vaccine care', 'fever after vaccine', 'soothing'],
      url: 'https://www.youtube.com/results?search_query=how+to+soothe+baby+after+vaccine+shots',
      description: 'Managing mild fever and soreness after baby shots.',
      emoji: '🩺',
    },
  ],

  'Baby Safety': [
    {
      id: 'bsf1',
      title: 'Infant Safety & Preventing Household Accidents',
      category: 'Baby Safety',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['safety', 'prevention', 'baby proofing'],
      url: 'https://www.youtube.com/results?search_query=infant+safety+and+baby+proofing+tips',
      description: 'Essential safety guidelines for handling, sleeping, and home safety.',
      emoji: '🛡️',
    },
    {
      id: 'bsf2',
      title: 'Baby Choking First Aid & Safe Sleep Guidelines',
      category: 'Baby Safety',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['choking', 'first aid', 'safe sleep'],
      url: 'https://www.youtube.com/results?search_query=infant+choking+first+aid+and+cpr',
      description: 'Emergency first-aid techniques and safe sleep practices for babies.',
      emoji: '⚠️',
    },
  ],

  'Mother Care': [
    {
      id: 'mc1',
      title: 'Postpartum Recovery Tips & Self Care for Mamas',
      category: 'Mother Care',
      ages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      tags: ['recovery', 'postpartum', 'self care'],
      url: 'https://www.youtube.com/results?search_query=postpartum+recovery+tips+for+new+moms',
      description: 'How to take care of your physical and emotional health after birth.',
      emoji: '🌸',
    },
  ],
};

export const getAllBabyVideos = () => {
  return Object.values(BABY_VIDEO_LIBRARY).flat();
};

